name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Build
      id: build
      run: make -j8 PREFIX="ccache aarch64-none-elf-"
      continue-on-error: true

    - name: Install libnx master & Retry build
      id: retry
      if: ${{ steps.build.outcome == 'failure' }}
      run: |
        pushd /tmp
        git clone https://github.com/switchbrew/libnx
        cd libnx
        make -j8 PREFIX="ccache aarch64-none-elf-"
        make install
        popd
        make -j8 PREFIX="ccache aarch64-none-elf-"

    - name: Pack
      run: |
        # The devkitpro container runs as root and ships without sudo or zip.
        apt-get update && apt-get install -y zip
        cd ./out/sd
        zip -r ./ldn_mitm_${{ env.RELEASE_VERSION }}.zip atmosphere switch

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.RELEASE_VERSION }}
        files: out/sd/ldn_mitm_${{ env.RELEASE_VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
